@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml

interface Doclet{}
interface Option {}
interface DocletEnvironement {}
interface Reporter
interface Taglet

class StandartDoclet

enum Kind
enum ModuleMode
enum Location

@enduml