@startuml
skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

interface Doclet <<interface>>
interface Reporter <<interface>>

interface Option <<interface>>

interface DocletEnvironnement <<interface>>

interface Taglet <<interface>>

class StandardDoclet implements Doclet

enum Kind <<enum>>
{
    EXTENDED
    OTHER
    STANDAR
}

enum Location <<enum>>
{
    CONSTRUCTOR
    FIELD
    METHOD
    MODULE
    OVERVIEW
    PACKAGE
    TYPE
}

enum ModuleMode <<enum>>
{
    ALL
    API
}

Taglet - Location
DocletEnvironnement - ModuleMode
Doclet -Option
Option - Kind
@enduml