@startuml
skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

interface Doclet <<interface>>
interface Option <<interface>>
interface DocletEnvironnement <<interface>>
interface Taglet <<interface>>

class StandardDoclet implements Doclet {
    + <<create>> StandardDoclet()
    + init(locale :Locale, reporter: Reporter)
    + getName(): String
    + getSupportedOptions() :
    + getSupportedSourceVersion(): SourceVersion
    + run(docEnv: DocletEnvironment): Boolean
    + getLocale(): Locale
    + getReporter(): Reporter
}

enum Kind <<enum>> extends Kind implements Kind
{
    EXTENDED
    OTHER
    STANDAR
    + {static}values():
    + {static}valueOf(name: String)
}

enum Location <<enum>> extends Location implements Location
{
    CONSTRUCTOR
    FIELD
    METHOD
    MODULE
    OVERVIEW
    PACKAGE
    TYPE
    + {static}values():
    + {static}valueOf(name: String)
}

enum ModuleMode <<enum>> extends ModuleMode implements ModuleMode
{
    ALL
    API
    + {static}values():
    + {static}valueOf(name: String)
}

Taglet - Location
DocletEnvironnement - ModuleMode
Option - Kind
@enduml