@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

interface PumlElement <<interface>>{
    + getPumlCode() : String
    + getSimpleName() : String
}

class PumlPackage {
    - element : Element
    - elements : pumlElement[]
    + <<Create>> pumlPackage(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getKind() : String
}

class PumlClass {
    - element : Element
    - attributs : pumlAttribut[]
    - elements : pumlMethod[]
    + <<Create>> pumlClass(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getKind() : String
    + getAccessLevel() : String
    - getAttributs() : String
    - getMethods() : String
}

class PumlEnum {
    - element : Element
    - attributs : pumlEnumAttribut[]
    - elements : pumlMethod[]
    + <<Create>> pumlEnum(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getAccessLevel() : String
}

class PumlEnumAttribut {
    + <<Create>> pumlEnumAttribut(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
}

class PumlInterface {
    - element : Element
    - elements : pumlMethod[]
    + <<Create>> pumlInterface(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getAccessLevel() : String
}

class PumlMethod {
    - element : Element
    - parameters : pumlParameter[]
    + <<Create>> pumlMethod(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getAccessLevel() : String
    + getOthersModifiers() : String
    + getAttributs() : String
}

class PumlConstructor {
    - element : Element
    - parameters : pumlParameter[]
    + <<Create>> pumlMethod(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getAccessLevel() : String
    + getOthersModifiers() : String
    + getAttributs() : String
}


class PumlAttribut {
    + <<Create>> pumlAttribut(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getType() : String
    + getAccessLevel() : String
    + getOthersModifiers() : String
}

class PumlParameter {
    + <<Create>> pumlParameter(element : Element)
    + getPumlCode() : String
    + getSimpleName() : String
    + getType() : String
}

class PumlDiagram {
    + <<Create>> pumlDiagram()
    + generatePuml(fileName : String, path : String, code : String)
}

PumlPackage ..d|> PumlElement
PumlClass ..d|> PumlElement
PumlEnum ..d|> PumlElement
PumlInterface ..d|> PumlElement
PumlMethod ..|> PumlElement
PumlConstructor ..l|> PumlMethod
PumlAttribut ..u|> PumlElement
PumlEnumAttribut ..u|> PumlElement
PumlParameter ..u|> PumlElement

PumlPackage *-> PumlClass
PumlPackage *-> PumlEnum
PumlPackage *-> PumlInterface
PumlClass *-> PumlMethod
PumlEnum *-> PumlMethod
PumlInterface *-> PumlMethod
PumlClass *-> PumlAttribut
PumlEnum *-> PumlEnumAttribut
PumlMethod *-> PumlParameter

@enduml