@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

interface pumlElement <<interface>>{
    + getPumlCode() : String
    + getSimpleName() : String
}

class pumlPackage {
    + <<Create>> pumlPackage(element : Element)
    + getPumlCode() : String
    + getKind() : String
}

class pumlClass {
    + <<Create>> pumlClass(element : Element)
    + getPumlCode() : String
    + getAccessLevel() : String
    + isAbstract() : boolean
'System.out.println(element.getModifiers().contains(Modifier.ABSTRACT));
}

class pumlEnum {
    + <<Create>> pumlEnum(element : Element)
    + getPumlCode() : String
    + getAccessLevel() : String
}

class pumlEnumAttribut {
    + <<Create>> pumlEnumAttribut(element : Element)
    + getPumlCode() : String
}

class pumlInterface {
    + <<Create>> pumlInterface(element : Element)
    + getPumlCode() : String
    + getAccessLevel() : String
}

class pumlMethod {
    + <<Create>> pumlMethod(element : Element)
    + getPumlCode() : String
    + getAccessLevel() : String
    + isAbstract() : boolean
}


class pumlAttribut {
    + <<Create>> pumlAttribut(element : Element)
    + getPumlCode() : String
    + getAccessLevel() : String
    + getType() : String
    + getName() : String
}

class pumlParameter {
    + <<Create>> pumlParameter(element : Element)
    + getPumlCode() : String
    + getType() : String
    + getName() : String
}

class pumlDiagram {
    + <<Create>> pumlDiagram()
    + generatePuml(fileName : String, path : String, code : String)
}

pumlPackage ..l|> pumlElement
pumlClass ..d|> pumlElement
pumlEnum ..d|> pumlElement
pumlInterface ..d|> pumlElement
pumlMethod ..r|> pumlElement
pumlAttribut ..u|> pumlElement
pumlEnumAttribut ..u|> pumlElement
pumlParameter ..u|> pumlElement

@enduml