@startuml

'Code généré automatiquement ;>
skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam classbackgroundColor LightGoldenRodYellow
skinparam classbordercolor red
skinparam classattribute none
skinparam classborderthickness 2

package western{
enum Genre <<enum>> {
	FEMININ
	MASCULIN

}
class Boisson {
}
	Boisson - western.Substantif

class Substantif {
	nom
}
	Substantif - western.Genre

class Histoire1 {
}

class Histoire4 {
}

class Personnage {
	nom
}
	
	Personnage - western.Boisson

class Narrateur extends western.Personnage {
}

class Brigand extends western.Personnage implements western.HorsLaLoi {
	estLibre
	look
	prime
}
	Brigand - western.Cowboy
	Brigand -> western.Dame

interface HorsLaLoi <<interface>> {}

class Cowboy extends western.Personnage {
	replique
	recompense
}
	Cowboy -> western.HorsLaLoi

class Dame extends western.Personnage {
	estlibre
}
	Dame - western.HorsLaLoi

class Histoire3 {
}

class Ripou extends western.Cowboy implements western.HorsLaLoi {
}
	Ripou - western.Brigand

class HistoireTest {
}

}


@enduml