@startuml
'Code généré automatiquement ;>
skinparam style strictuml
hide empty members
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam classbackgroundColor LightGoldenRodYellow
skinparam classbordercolor red
skinparam classattribute none
skinparam classborderthickness 2

package western {

class Boisson {
	substantif
}
class Brigand {
	estLibre
	look
	prime
	geolier
	sesDames
}
class Cowboy {
	replique
	recompense
	vilains
}
class Dame {
	estlibre
	geolier
}
enum Genre {
	FEMININ
	MASCULIN
}
class Histoire1 {
}
class Histoire3 {
}
class Histoire4 {
}
class HistoireTest {
}
interface HorsLaLoi {
}
class Narrateur {
}
class Personnage {
	BOISSON_PAR_DEFAUT
	nom
	boisson
}
class Ripou {
	brigand
}
class Substantif {
	nom
	genre
}
}
@enduml